# Laura V. Oliveros M.
# Física Computacional 1


# reglas para decirle a make que vamos a contruir desde el archivo cpp
caidalibre: caidalibre.cpp
	g++ -o caidalibre caidalibre.cpp



# esta regla le indica a make que borre hello y hello.o
.PHONY: clean
clean: 
	rm -f caidalibre